# Generated by Django 4.2 on 2023-04-19 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_producto_carrito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombreCompleto', models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='Nombre Completo Usuario')),
                ('correo', models.CharField(max_length=60, verbose_name='Correo Usuario')),
                ('numeroTelefono', models.IntegerField(verbose_name='Numero Usuario')),
                ('Credencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.credencial')),
            ],
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
