# Generated by Django 4.2 on 2023-05-02 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_juego_delete_mascota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Credencial',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Credencial',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
