# Generated by Django 4.2 on 2023-04-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idGenero', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Genero')),
                ('nnombreGenero', models.CharField(max_length=50, verbose_name='Nombre de Genero')),
            ],
        ),
        migrations.DeleteModel(
            name='Credencial',
        ),
    ]
