# Generated by Django 4.2 on 2023-04-19 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usuario_delete_carrito_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='Id Producto')),
                ('nombreProducto', models.CharField(max_length=60, verbose_name='Nombre Producto')),
                ('categoria', models.IntegerField(verbose_name='Categoria')),
            ],
        ),
    ]
