# Generated by Django 4.2 on 2023-04-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='username')),
                ('password', models.CharField(max_length=20, verbose_name='password')),
            ],
        ),
    ]
