# Generated by Django 4.2 on 2023-04-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoChip', models.IntegerField(verbose_name='Id chip')),
                ('nombreMascota', models.CharField(max_length=60, verbose_name='Nombre Mascota')),
                ('edadMascota', models.IntegerField(verbose_name='edad Mascota')),
                ('raza', models.IntegerField(verbose_name='edad Mascota')),
            ],
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='password',
            field=models.CharField(max_length=20, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='username',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Username'),
        ),
    ]
