# Generated by Django 4.2 on 2023-04-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_mascota_alter_cuenta_password_alter_cuenta_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cuenta',
        ),
        migrations.AlterField(
            model_name='mascota',
            name='raza',
            field=models.IntegerField(verbose_name='Raza'),
        ),
    ]
